/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/api/wrangler.jsonc --include-runtime=false apps/api/cloudflare/worker-configuration.d.ts` (hash: 5454ee5e71d8bd57ed5f9741d29231c4)
interface __BaseEnv_Env {
  ACCOUNT_BASE_URL: "https://synara-account-api-trial.synara-orgs.workers.dev";
  API_PUBLIC_URL: "https://synara-account-api-trial.synara-orgs.workers.dev/api/v1";
  DATABASE_URL: string;
  WORKOS_API_KEY: string;
  WORKOS_CLIENT_ID: string;
  API_SIGNING_KEY: string;
  ACCOUNT_API: DurableObjectNamespace<import("./worker").AccountApi>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "AccountApi";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ACCOUNT_BASE_URL"
      | "API_PUBLIC_URL"
      | "DATABASE_URL"
      | "WORKOS_API_KEY"
      | "WORKOS_CLIENT_ID"
      | "API_SIGNING_KEY"
    >
  > {}
}
