export const PWA_SHELL_URL = "/index.html";
export const PWA_BYPASS_PATHS = ["/api", "/pair", "/signed-out"] as const;

export function shouldBypassPwaPath(pathname: string): boolean {
  return PWA_BYPASS_PATHS.some(
    (path) => pathname === path || pathname.startsWith(`${path}/`),
  );
}

interface ServiceWorkerSourceOptions {
  readonly cacheVersion: string;
  readonly precacheUrls: readonly string[];
}

export function createPwaServiceWorkerSource({
  cacheVersion,
  precacheUrls,
}: ServiceWorkerSourceOptions): string {
  const uniquePrecacheUrls = [...new Set(precacheUrls)].sort();

  return `/* Generated by apps/web/vite.config.ts. Do not edit the build output. */
const CACHE_PREFIX = "synara-web-";
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(cacheVersion)};
const SHELL_URL = ${JSON.stringify(PWA_SHELL_URL)};
const PRECACHE_URLS = ${JSON.stringify(uniquePrecacheUrls)};
const PRECACHE_PATHS = new Set(PRECACHE_URLS.map((url) => new URL(url, self.location.origin).pathname));
const BYPASS_PATHS = ${JSON.stringify(PWA_BYPASS_PATHS)};

function bypassRequest(request, url) {
  return request.method !== "GET" ||
    url.origin !== self.location.origin ||
    request.headers.has("authorization") ||
    BYPASS_PATHS.some((path) => url.pathname === path || url.pathname.startsWith(path + "/"));
}

async function networkFirstNavigation(request, url) {
  try {
    const response = await fetch(request);
    if (response.ok && (url.pathname === "/" || url.pathname === SHELL_URL)) {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(SHELL_URL, response.clone());
    }
    return response;
  } catch {
    return (await caches.match(SHELL_URL, { cacheName: CACHE_NAME })) || Response.error();
  }
}

async function cacheFirstStatic(request) {
  const cached = await caches.match(request, { cacheName: CACHE_NAME });
  if (cached) return cached;

  const response = await fetch(request);
  if (response.ok && response.type === "basic") {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(request, response.clone());
  }
  return response;
}

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name))),
    ),
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (bypassRequest(request, url)) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirstNavigation(request, url));
    return;
  }

  if (url.pathname.startsWith("/assets/") || PRECACHE_PATHS.has(url.pathname)) {
    event.respondWith(cacheFirstStatic(request));
  }
});
`;
}
