/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatReviewRouteImport } from './routes/_chat.review'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatWorkspaceIndexRouteImport } from './routes/_chat.workspace.index'
import { Route as ChatReviewIndexRouteImport } from './routes/_chat.review.index'
import { Route as ChatWorkspaceWorkspaceIdRouteImport } from './routes/_chat.workspace.$workspaceId'
import { Route as ChatReviewReferenceRouteImport } from './routes/_chat.review.$reference'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatReviewRoute = ChatReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorkspaceIndexRoute = ChatWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatReviewIndexRoute = ChatReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatReviewRoute,
} as any)
const ChatWorkspaceWorkspaceIdRoute =
  ChatWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatReviewReferenceRoute = ChatReviewReferenceRouteImport.update({
  id: '/$reference',
  path: '/$reference',
  getParentRoute: () => ChatReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/review': typeof ChatReviewRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/review/$reference': typeof ChatReviewReferenceRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/review/': typeof ChatReviewIndexRoute
  '/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/review/$reference': typeof ChatReviewReferenceRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/review': typeof ChatReviewIndexRoute
  '/workspace': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/review': typeof ChatReviewRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/review/$reference': typeof ChatReviewReferenceRoute
  '/_chat/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/_chat/review/': typeof ChatReviewIndexRoute
  '/_chat/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/plugins'
    | '/review'
    | '/settings'
    | '/review/$reference'
    | '/workspace/$workspaceId'
    | '/review/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/'
    | '/review/$reference'
    | '/workspace/$workspaceId'
    | '/review'
    | '/workspace'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/plugins'
    | '/_chat/review'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/review/$reference'
    | '/_chat/workspace/$workspaceId'
    | '/_chat/review/'
    | '/_chat/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/review': {
      id: '/_chat/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ChatReviewRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/workspace/': {
      id: '/_chat/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof ChatWorkspaceIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/review/': {
      id: '/_chat/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ChatReviewIndexRouteImport
      parentRoute: typeof ChatReviewRoute
    }
    '/_chat/workspace/$workspaceId': {
      id: '/_chat/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof ChatWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/review/$reference': {
      id: '/_chat/review/$reference'
      path: '/$reference'
      fullPath: '/review/$reference'
      preLoaderRoute: typeof ChatReviewReferenceRouteImport
      parentRoute: typeof ChatReviewRoute
    }
  }
}

interface ChatReviewRouteChildren {
  ChatReviewReferenceRoute: typeof ChatReviewReferenceRoute
  ChatReviewIndexRoute: typeof ChatReviewIndexRoute
}

const ChatReviewRouteChildren: ChatReviewRouteChildren = {
  ChatReviewReferenceRoute: ChatReviewReferenceRoute,
  ChatReviewIndexRoute: ChatReviewIndexRoute,
}

const ChatReviewRouteWithChildren = ChatReviewRoute._addFileChildren(
  ChatReviewRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatReviewRoute: typeof ChatReviewRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatWorkspaceWorkspaceIdRoute: typeof ChatWorkspaceWorkspaceIdRoute
  ChatWorkspaceIndexRoute: typeof ChatWorkspaceIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatReviewRoute: ChatReviewRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatWorkspaceWorkspaceIdRoute: ChatWorkspaceWorkspaceIdRoute,
  ChatWorkspaceIndexRoute: ChatWorkspaceIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
