// FILE: avatarStorage.ts
// Purpose: The object-storage seam behind profile avatar uploads. Routes
// depend on the small AvatarStorage interface only; the concrete
// implementation is a minimal AWS SigV4 client for any S3-compatible store
// (Cloudflare R2, MinIO, AWS S3, …) — deliberately not the AWS SDK, which
// would add a dependency tree three orders of magnitude larger than the two
// requests this service makes.
// Layer: API storage adapter
// Depends on: node:crypto, config (AvatarStorageConfig) only.

import { createHash, createHmac } from "node:crypto";
import type { AvatarStorageConfig } from "./config";

/**
 * What the routes need from object storage — small on purpose so tests can
 * hand the routes a fake instead of a network.
 */
export interface AvatarStorage {
  /** Writes an object. Throws on any non-2xx answer from the store. */
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
  /** Deletes an object. Throws on failure; callers decide whether that matters. */
  delete(key: string): Promise<void>;
  /** The public URL an uploaded key is served from. */
  publicUrl(key: string): string;
}

const SIGV4_SERVICE = "s3";

/**
 * Abort deadline on every storage request, mirroring the identity provider's
 * bounded fetches (WORKOS_REQUEST_TIMEOUT_MS): a stalling endpoint must fail
 * the RPC, never hang it. Generous for the payload — avatars are ≤2MB.
 */
export const AVATAR_STORAGE_TIMEOUT_MS = 30_000;

/**
 * Uploaded avatars are immutable by construction — the key contains the
 * content hash, so a changed avatar is a new key — which is what makes a
 * year-long immutable cache lifetime safe.
 */
const AVATAR_CACHE_CONTROL = "public, max-age=31536000, immutable";

function sha256Hex(data: Uint8Array | string): string {
  return createHash("sha256").update(data).digest("hex");
}

function hmac(key: Uint8Array | string, data: string): Buffer {
  return createHmac("sha256", key).update(data).digest();
}

/**
 * An S3-compatible client speaking AWS Signature Version 4 over path-style
 * URLs (`https://{endpoint-host}/{bucket}/{key}`). The signing region comes
 * from config (S3_REGION): "auto" by default — the spelling R2 requires and
 * MinIO accepts — while real AWS wants the bucket's actual region.
 */
export function createAvatarStorage(
  config: AvatarStorageConfig,
  fetchFn: typeof fetch = fetch,
  // Overridable the same way the identity provider's request timeout is —
  // production always takes the default; tests shrink it.
  timeoutMs: number = AVATAR_STORAGE_TIMEOUT_MS,
): AvatarStorage {
  const endpoint = new URL(config.endpoint);
  const region = config.region;

  async function signedRequest(
    method: "PUT" | "DELETE",
    key: string,
    body: Uint8Array | undefined,
    extraHeaders: Record<string, string>,
  ): Promise<void> {
    // Keys are generated by this service (hex hash + fixed extension), so
    // every character is URI-safe except the path separators, which S3 wants
    // kept literal in the canonical path.
    const canonicalPath = `/${config.bucket}/${key
      .split("/")
      .map((segment) => encodeURIComponent(segment))
      .join("/")}`;
    const now = new Date();
    const amzDate = now
      .toISOString()
      .replace(/[-:]/g, "")
      .replace(/\.\d{3}Z$/, "Z");
    const dateStamp = amzDate.slice(0, 8);
    const payloadHash = sha256Hex(body ?? "");

    const headers: Record<string, string> = {
      host: endpoint.host,
      "x-amz-content-sha256": payloadHash,
      "x-amz-date": amzDate,
      ...extraHeaders,
    };
    const signedHeaderNames = Object.keys(headers)
      .map((name) => name.toLowerCase())
      .sort();
    const canonicalHeaders = signedHeaderNames
      .map((name) => `${name}:${headers[name]!.trim()}\n`)
      .join("");
    const signedHeaders = signedHeaderNames.join(";");

    const canonicalRequest = [
      method,
      canonicalPath,
      "", // no query string on either request this client makes
      canonicalHeaders,
      signedHeaders,
      payloadHash,
    ].join("\n");

    const credentialScope = `${dateStamp}/${region}/${SIGV4_SERVICE}/aws4_request`;
    const stringToSign = [
      "AWS4-HMAC-SHA256",
      amzDate,
      credentialScope,
      sha256Hex(canonicalRequest),
    ].join("\n");

    const signingKey = hmac(
      hmac(hmac(hmac(`AWS4${config.secretAccessKey}`, dateStamp), region), SIGV4_SERVICE),
      "aws4_request",
    );
    const signature = createHmac("sha256", signingKey).update(stringToSign).digest("hex");

    let response: Response;
    try {
      response = await fetchFn(`${endpoint.origin}${canonicalPath}`, {
        method,
        headers: {
          ...headers,
          authorization:
            `AWS4-HMAC-SHA256 Credential=${config.accessKeyId}/${credentialScope}, ` +
            `SignedHeaders=${signedHeaders}, Signature=${signature}`,
        },
        ...(body !== undefined ? { body } : {}),
        signal: AbortSignal.timeout(timeoutMs),
      });
    } catch (error) {
      // Surface the abort as the same error shape a failed status throws, so
      // callers keep one storage-failure path; the cause carries the detail.
      if (error instanceof DOMException && error.name === "TimeoutError") {
        throw new Error(`avatar storage ${method} ${key} timed out after ${timeoutMs}ms`, {
          cause: error,
        });
      }
      throw error;
    }
    // Deletes of a missing key answer 404 on some stores and 204 on others;
    // both mean "the object is gone", which is all a caller ever wants.
    if (!response.ok && !(method === "DELETE" && response.status === 404)) {
      throw new Error(`avatar storage ${method} ${key} failed with status ${response.status}`);
    }
  }

  return {
    async put(key, body, contentType) {
      await signedRequest("PUT", key, body, {
        "content-type": contentType,
        "cache-control": AVATAR_CACHE_CONTROL,
      });
    },
    async delete(key) {
      await signedRequest("DELETE", key, undefined, {});
    },
    publicUrl(key) {
      return `${config.publicBaseUrl}/${key}`;
    },
  };
}
