// FILE: uiLanguage.ts
// Purpose: Resolve the preferred interface language and translate fixed application chrome.
// Layer: Web UI support

export const UI_LANGUAGE_OPTIONS = ["system", "en", "zh-CN"] as const;
export type UiLanguagePreference = (typeof UI_LANGUAGE_OPTIONS)[number];
export type ResolvedUiLanguage = Exclude<UiLanguagePreference, "system">;

const SIMPLIFIED_CHINESE_TEXT: Readonly<Record<string, string>> = {
  "App": "应用",
  "AppSnap": "AppSnap",
  "AppSnap is available only in the macOS desktop app.": "AppSnap 仅适用于 macOS 桌面应用。",
  "AppSnap requires the Synara desktop app on macOS.": "AppSnap 需要使用 macOS 桌面应用。",
  "Appearance": "外观",
  "Archived": "已归档",
  "Automatic": "自动",
  "Available in the Synara desktop app": "可在 Synara 桌面应用中使用",
  "Available on macOS only": "仅适用于 macOS",
  "Back to app": "返回应用",
  "Behavior": "行为",
  "Capture": "捕获",
  "Capture sound": "捕获提示音",
  "Chats": "聊天",
  "Denied": "已拒绝",
  "Controls how projects are arranged in the main sidebar.": "控制项目在主侧边栏中的排列方式。",
  "Controls how threads are arranged inside each project in the main sidebar.": "控制每个项目内线程的排列方式。",
  "Choose the provider used for new chats.": "选择新建聊天使用的服务商。",
  "Core defaults": "核心默认设置",
  "capture sound": "捕获提示音",
  "chats section": "聊天分区",
  "default provider": "默认服务商",
  "Default provider": "默认服务商",
  "Default thread mode": "默认线程模式",
  "Default provider, thread mode, and sidebar organization.": "默认服务商、线程模式与侧边栏组织方式。",
  "Destination": "目标位置",
  "Enable AppSnap": "启用 AppSnap",
  "English": "英文",
  "Environment panel": "环境面板",
  "environment panel default open": "环境面板默认打开",
  "Granted": "已授予",
  "General": "常规",
  "Input Monitoring": "输入监控",
  "Listening — press both Option keys to snap": "正在监听 — 同时按下左右 Option 键即可捕获",
  "Keyboard Shortcuts": "键盘快捷键",
  "Language": "界面语言",
  "Local": "本地",
  "Lets Synara capture an image of the frontmost window. Only the single window you snap is captured, only at the moment you press the chord.": "允许 Synara 捕获前台窗口的图像。仅会在你按下组合键的瞬间捕获你指定的单个窗口。",
  "Lets Synara notice the double-Option chord while another app owns the keyboard. Nothing you type is recorded.": "允许 Synara 在其他应用使用键盘时识别双 Option 组合键；不会记录你输入的任何内容。",
  "macOS permissions": "macOS 权限",
  "Models": "模型",
  "New threads": "新建线程",
  "New worktree": "新建工作树",
  "new threads": "新建线程",
  "Not requested yet": "尚未请求",
  "Notepad": "记事本",
  "Newest first": "最新优先",
  "No matching settings.": "没有匹配的设置。",
  "Notifications": "通知",
  "Pick the default workspace mode for newly created draft threads.": "为新创建的草稿线程选择默认工作区模式。",
  "Play a short shutter cue when a window is captured.": "捕获窗口时播放简短的快门提示音。",
  "Play a sound when an AppSnap is captured": "捕获 AppSnap 时播放提示音",
  "Press both Option keys at once while any app is frontmost. Synara captures that window as an image, brings itself forward, and attaches the snap to a task composer — the capture stays on this device until you send the message.": "当前台显示任意应用时，同时按下左右两个 Option 键。Synara 会将该窗口捕获为图片、自动切回前台并附加到任务输入框；在你发送消息前，捕获内容始终保留在本机。",
  "Press the left and right Option keys at the same time. The chord works while any app is focused, and can't be remapped yet.": "同时按下左右两个 Option 键。任意应用获得焦点时都能使用此组合键，目前暂不支持重新映射。",
  "Preview": "预览",
  "Permission status": "权限状态",
  "Permission setup required": "需要配置权限",
  "pinned messages section": "置顶消息分区",
  "Profile": "个人资料",
  "Project order": "项目排序",
  "project order": "项目排序",
  "Project instructions": "项目指令",
  "Project sort order": "项目排序",
  "Providers": "服务商",
  "Recently active": "最近活跃",
  "Recently added": "最近添加",
  "Recheck permissions": "重新检查权限",
  "Recap": "回顾",
  "recap section": "回顾分区",
  "repository section": "仓库分区",
  "Repository": "仓库",
  "Restricted": "受限",
  "Restore defaults": "恢复默认设置",
  "Run the capture listener in the background while Synara is open.": "在 Synara 打开期间于后台运行捕获监听器。",
  "Screen Recording": "屏幕录制",
  "Search settings": "搜索设置",
  "Search settings...": "搜索设置…",
  "Shortcut": "快捷键",
  "Starting the capture listener…": "正在启动捕获监听器…",
  "studio section": "工作室分区",
  "Show the Chats section in the sidebar": "在侧边栏显示聊天分区",
  "Show the Studio section in the sidebar": "在侧边栏显示工作室分区",
  "Show the Workspace section in the sidebar": "在侧边栏显示工作区分区",
  "Show the standalone Chats list in the sidebar footer (chats not tied to a project).": "在侧边栏底部显示独立的聊天列表（不属于任何项目的聊天）。",
  "Show the Studio tab in the sidebar switcher.": "在侧边栏切换器中显示“工作室”标签。",
  "Show the Workspace tab in the sidebar switcher. The Threads tab always stays visible.": "在侧边栏切换器中显示“工作区”标签。“线程”标签始终可见。",
  "Sidebar organization": "侧边栏组织",
  "Sidebar sections": "侧边栏分区",
  "Snap another app's window straight into a task with one key chord.": "通过一个组合键，将其他应用的窗口直接捕获到任务中。",
  "Snaps join the task you interacted with in the last minute, and consecutive snaps stay together. Otherwise Synara opens a fresh task with the capture attached.": "捕获内容会加入你最近一分钟内操作过的任务，连续捕获会归到同一任务；否则 Synara 会新建一个附带捕获内容的任务。",
  "Studio": "工作室",
  "Skills": "技能",
  "Simplified Chinese": "简体中文",
  "System default": "跟随系统",
  "Take an AppSnap to show your agent another app's window": "使用 AppSnap 向代理展示其他应用的窗口",
  "The language used for Synara's fixed interface text. Chat messages, code, and terminal output are never translated.": "用于 Synara 固定界面文案的语言。不会翻译聊天消息、代码和终端输出。",
  "Thread order": "线程排序",
  "thread order": "线程排序",
  "Thread sort order": "线程排序",
  "Manual order": "手动排序",
  "Off": "关闭",
  "Worktrees": "工作树",
  "Workspace": "工作区",
  "Unknown": "未知",
  "Usage": "用量",
  "usage section": "用量分区",
  "workspace section": "工作区分区",
  "Open the chat Environment panel automatically on normal threads. When off, the panel stays closed until you open it. Your last open/close also updates this preference.": "在普通线程中自动打开聊天环境面板。关闭后，面板会保持关闭，直到你手动打开；你最近一次的开关操作也会更新此偏好。",
  "Show the provider usage row in the chat Environment panel.": "在聊天环境面板中显示服务商用量行。",
  "Show the GitHub repository link in the chat Environment panel. The git block (Changes, Worktree, branch, Commit and Push) always stays visible.": "在聊天环境面板中显示 GitHub 仓库链接。Git 区块（更改、工作树、分支、提交和推送）始终可见。",
  "Show the open pull request (CI checks and review comments) for the current branch in the chat Environment panel.": "在聊天环境面板中显示当前分支的开放拉取请求（CI 检查与评审评论）。",
  "Show the Editor section (in-app editor view and Open in editor picker) in the chat Environment panel.": "在聊天环境面板中显示编辑器分区（应用内编辑器视图和“在编辑器中打开”选择器）。",
  "Show the auto-generated chat recap in the Environment panel.": "在环境面板中显示自动生成的聊天回顾。",
  "Show the pinned-messages checklist in the Environment panel.": "在环境面板中显示置顶消息清单。",
  "Show highlighted and underlined transcript text in the Environment panel.": "在环境面板中显示高亮和带下划线的对话文本。",
  "Show project-level instructions in the Environment panel.": "在环境面板中显示项目级指令。",
  "Show the per-thread notepad in the Environment panel.": "在环境面板中显示每个线程的记事本。",
  "Grant both permissions to Synara under System Settings → Privacy & Security, then recheck here. macOS may require relaunching the app after a change.": "请在“系统设置 → 隐私与安全性”中向 Synara 授予两项权限，然后在此重新检查。更改后，macOS 可能要求重新启动应用。",
  "Open the Environment panel by default on normal threads": "在普通线程中默认打开环境面板",
  "Show the Usage section in the Environment panel": "在环境面板中显示用量分区",
  "Show the Repository section in the Environment panel": "在环境面板中显示仓库分区",
  "Show the Pull request section in the Environment panel": "在环境面板中显示拉取请求分区",
  "Show the Editor section in the Environment panel": "在环境面板中显示编辑器分区",
  "Show the Recap section in the Environment panel": "在环境面板中显示回顾分区",
  "Show the Pinned messages section in the Environment panel": "在环境面板中显示置顶消息分区",
  "Show the Text markers section in the Environment panel": "在环境面板中显示文本标记分区",
  "Show the Project instructions section in the Environment panel": "在环境面板中显示项目指令分区",
  "Show the Notepad section in the Environment panel": "在环境面板中显示记事本分区",
  "Open by default": "默认打开",
  "Pull request": "拉取请求",
  "Editor": "编辑器",
  "Pinned messages": "置顶消息",
  "Text markers": "文本标记",
  "Advanced": "高级",
  "Integrations": "集成",
  "Activity alerts": "活动提醒",
  "Activity toast notifications": "活动提示通知",
  "Activity toasts": "活动提示",
  "Accent": "强调色",
  "Archive confirmation": "归档确认",
  "Ask before archiving a thread.": "归档线程前进行确认。",
  "Ask before closing a terminal tab and clearing its history.": "关闭终端标签页并清除其历史记录前进行确认。",
  "Ask before deleting a thread and its chat history.": "删除线程及其聊天记录前进行确认。",
  "Assistant output": "助手输出",
  "Background": "背景",
  "Base font size": "基础字号",
  "Base font size in pixels": "基础字号（像素）",
  "Choose how Synara looks across the app.": "选择 Synara 在整个应用中的外观。",
  "Code font": "代码字体",
  "Compact": "紧凑",
  "Comfortable": "舒适",
  "Confirm terminal tab close": "确认关闭终端标签页",
  "Confirm thread archive": "确认归档线程",
  "Confirm thread deletion": "确认删除线程",
  "Contrast": "对比度",
  "Control spacing in the sidebar, composer, chat gutters, and settings rows without changing font size.": "在不改变字号的前提下，调整侧边栏、输入框、聊天边距和设置行的间距。",
  "Dark": "深色",
  "Dark theme": "深色主题",
  "Delete confirmation": "删除确认",
  "Desktop activity notifications": "桌面活动通知",
  "Desktop notifications": "桌面通知",
  "Diff line wrapping": "差异行换行",
  "Enable font smoothing": "启用字体平滑",
  "Font smoothing": "字体平滑",
  "Foreground": "前景色",
  "Ignore the theme's custom UI font and render the interface with the native system font (SF Pro on macOS).": "忽略主题的自定义界面字体，并使用原生系统字体渲染界面（macOS 上为 SF Pro）。",
  "Light": "浅色",
  "Light theme": "浅色主题",
  "No matching suggested fonts.": "没有匹配的推荐字体。",
  "Set the default wrap state when the diff panel opens. The in-panel wrap toggle only affects the current diff session.": "设置差异面板打开时的默认换行状态。面板内的换行开关仅影响当前差异会话。",
  "Show an in-app toast when a chat or managed terminal agent finishes or needs input.": "当聊天或受管终端代理完成任务、需要输入时，显示应用内提示。",
  "Show an OS notification when a chat or managed terminal agent finishes or needs input while the app is in the background.": "当应用位于后台且聊天或受管终端代理完成任务、需要输入时，显示系统通知。",
  "Show token-by-token output while a response is in progress.": "在响应生成过程中逐词显示输出。",
  "Spacious": "宽松",
  "Stream assistant messages": "流式显示助手消息",
  "System": "系统",
  "System default follows your browser or OS clock preference.": "跟随系统会使用浏览器或操作系统的时钟偏好。",
  "Terminal close confirmation": "关闭终端确认",
  "Terminal font": "终端字体",
  "Terminal font family": "终端字体族",
  "Terminal font size": "终端字号",
  "Test": "测试",
  "Theme": "主题",
  "Theme and typography": "主题与字体",
  "Theme preference": "主题偏好",
  "Time and reading": "时间与阅读",
  "Time format": "时间格式",
  "Timestamp format": "时间格式",
  "Translucent sidebar": "半透明侧边栏",
  "UI density": "界面密度",
  "UI font": "界面字体",
  "Use macOS-style antialiasing for lighter, crisper text rendering.": "使用 macOS 风格的抗锯齿，让文字显示更轻盈清晰。",
  "Use system UI font": "使用系统界面字体",
  "Adjust the app text base in pixels. Chat and UI typography scale proportionally from this value.": "以像素调整应用基础字号。聊天和界面字体会按此值等比例缩放。",
  "Adjust terminal text independently from the app and chat font size.": "独立于应用和聊天字号调整终端文字大小。",
  "Type any monospace font installed on this device (e.g. Fira Code). Leave empty for the default. Fonts that aren't installed fall back to the system monospace.": "输入本设备已安装的任意等宽字体（例如 Fira Code）。留空则使用默认字体；未安装的字体会回退到系统等宽字体。",
  "Default (JetBrains Mono)": "默认（JetBrains Mono）",
  "12-hour": "12 小时制",
  "24-hour": "24 小时制",
  "Theme, typography, and timestamp formatting.": "主题、字体与时间格式。",
  "In-app toasts and desktop alerts.": "应用内提示与桌面提醒。",
  "Streaming, diff handling, and destructive confirmations.": "流式输出、差异处理与危险操作确认。",
  "Every keyboard shortcut available in Synara, grouped by context.": "按使用场景归类的全部 Synara 键盘快捷键。",
  "Review and clean up the worktrees created by Synara.": "查看并清理 Synara 创建的工作树。",
  "View and restore archived threads.": "查看并恢复已归档线程。",
  "Git writing defaults and custom model slugs.": "Git 文案默认设置与自定义模型标识。",
  "Choose visible providers, review CLI installs, and update provider tools.": "选择可见服务商、查看 CLI 安装并更新服务商工具。",
  "Every skill found across providers, with toggles to control availability.": "跨服务商发现的全部技能，并可通过开关控制可用性。",
  "Remaining quota and credits for each signed-in provider.": "每个已登录服务商的剩余额度与积分。",
  "Keybindings, recovery, and version info.": "键盘绑定、恢复工具与版本信息。",
  "Terminal font size in pixels": "终端字号（像素）",
  "Desktop app notifications use your operating system notification center.": "桌面应用通知使用操作系统的通知中心。",
  "Browser notifications are enabled for this app.": "已为此应用启用浏览器通知。",
  "Browser notifications are blocked. Re-enable them in your browser site settings.": "浏览器通知已被阻止。请在浏览器的网站设置中重新启用。",
  "Browser notifications need a secure context. Localhost works; plain HTTP does not.": "浏览器通知需要安全上下文；localhost 可用，普通 HTTP 不可用。",
  "This browser does not support desktop notifications.": "此浏览器不支持桌面通知。",
  "Allow browser notifications to get alerts when chats or terminal agents finish or need input in the background.": "允许浏览器通知，以便在聊天或终端代理后台完成任务、需要输入时接收提醒。",
  "Copy": "复制",
  "Import": "导入",
  "Reset": "重置",
  "Runtime behavior": "运行行为",
  "Safety confirmations": "安全确认",
  "System is currently using this dark slot.": "系统当前正在使用此深色主题槽位。",
  "System is currently using this light slot.": "系统当前正在使用此浅色主题槽位。",
  "This is the active theme right now.": "这是当前正在使用的主题。",
  "Used when your system switches to dark.": "系统切换为深色外观时使用。",
  "Used when your system switches to light.": "系统切换为浅色外观时使用。",
  "Inactive while the app is locked to dark.": "应用锁定为深色主题时不使用。",
  "Inactive while the app is locked to light.": "应用锁定为浅色主题时不使用。",
  "Inactive while the app is locked to system.": "应用跟随系统主题时不使用。",
  "Theme copied": "主题已复制",
  "Copy failed": "复制失败",
  "Copied the dark theme share string.": "已复制深色主题分享字符串。",
  "Copied the light theme share string.": "已复制浅色主题分享字符串。",
  "Unable to copy the theme share string.": "无法复制主题分享字符串。",
  "Import dark theme": "导入深色主题",
  "Import light theme": "导入浅色主题",
  "Theme share string": "主题分享字符串",
  "assistant output": "助手输出",
  "archive confirmation": "归档确认",
  "delete confirmation": "删除确认",
  "diff line wrapping": "差异行换行",
  "terminal close confirmation": "关闭终端确认",
  "Reset to default": "恢复默认设置",
  "Loading managed worktrees...": "正在加载受管工作树…",
  "Unable to load worktrees.": "无法加载工作树。",
  "No app-managed worktrees found yet.": "尚未找到由应用管理的工作树。",
  "Worktree": "工作树",
  "Conversations": "对话",
  "No conversations linked to this worktree.": "没有关联到此工作树的对话。",
  "Delete": "删除",
  "Linked conversations exist. Deleting will ask for confirmation.": "存在关联对话。删除前会要求确认。",
  "No archived threads": "没有已归档线程",
  "Archived threads will appear here and can be restored to the sidebar.": "已归档线程会显示在这里，并可恢复到侧边栏。",
  "Unknown project": "未知项目",
  "Restore": "恢复",
  "Generation defaults": "生成默认设置",
  "Git writing model": "Git 文案模型",
  "Used for generated commit messages, PR titles, and branch names.": "用于生成提交信息、PR 标题和分支名称。",
  "Git text generation model": "Git 文案生成模型",
  "git writing model": "Git 文案模型",
  "Custom models": "自定义模型",
  "Saved model slugs": "已保存的模型标识",
  "Add custom model slugs for supported providers.": "为受支持的服务商添加自定义模型标识。",
  "custom models": "自定义模型",
  "Custom model provider": "自定义模型服务商",
  "Add": "添加",
  "Show less": "收起",
  "Show more": "显示更多",
  "Provider picker": "服务商选择器",
  "Visible providers": "可见服务商",
  "Drag providers into your preferred picker order and hide the ones you don't use. The provider you're currently using on a thread always stays visible.": "拖动服务商以调整选择器顺序，并隐藏不使用的服务商。当前线程正在使用的服务商始终保持可见。",
  "All providers visible": "所有服务商均可见",
  "Custom order": "自定义排序",
  "provider picker": "服务商选择器",
  "Updates": "更新",
  "Automatic CLI update checks": "自动检查 CLI 更新",
  "Check Codex, Claude, and other provider CLIs for newer versions in the background.": "在后台检查 Codex、Claude 及其他服务商 CLI 是否有新版本。",
  "CLI update checks": "CLI 更新检查",
  "Provider updates": "服务商更新",
  "Review provider versions and update tools. Open a row only when you need binary overrides.": "查看服务商版本并更新工具。仅在需要覆盖二进制路径时展开对应行。",
  "No provider updates detected": "未检测到服务商更新",
  "Automatic checks off": "自动检查已关闭",
  "Update": "更新",
  "Updating": "正在更新",
  "A newer version is available, but Synara could not identify a safe one-click update command for this installation.": "有可用的新版本，但 Synara 无法为当前安装识别安全的一键更新命令。",
  "Installed CLIs": "已安装的 CLI",
  "Provider tools": "服务商工具",
  "Review installed provider tools that Synara can safely update.": "查看 Synara 可以安全更新的已安装服务商工具。",
  "Configured — enter a replacement or leave blank": "已配置 — 输入新值以替换，或留空",
  "OpenAI response WebSockets": "OpenAI 响应 WebSocket",
  "Session": "会话",
  "This browser": "此浏览器",
  "Revoke this browser session and close every live Synara connection it owns. A fresh pairing link is required to reconnect.": "撤销此浏览器会话并关闭它持有的所有 Synara 连接。重新连接需要新的配对链接。",
  "Authenticated as": "已认证身份",
  "Signing out...": "正在退出…",
  "Sign out": "退出登录",
  "Developer tools": "开发者工具",
  "Keybindings": "键盘绑定",
  "Open the persisted `keybindings.json` file to edit advanced bindings directly.": "打开持久化的 `keybindings.json` 文件，直接编辑高级绑定。",
  "Resolving keybindings path...": "正在解析键盘绑定路径…",
  "Opens in your preferred editor.": "将在首选编辑器中打开。",
  "Opening...": "正在打开…",
  "Adding...": "正在添加…",
  "Browse": "浏览",
  "Type path": "输入路径",
  "Project path": "项目路径",
  "Open file": "打开文件",
  "Recovery tools": "恢复工具",
  "Rebuild local project indexes without clearing existing chats when the local state gets out of sync.": "本地状态不同步时，重建本地项目索引而不清除现有聊天。",
  "Visible because projects exist but no chat history is currently available.": "因存在项目但当前没有可用聊天记录而显示。",
  "Shown automatically only when recovery actions are relevant.": "仅在恢复操作相关时自动显示。",
  "Repairing...": "正在修复…",
  "Repair state": "修复状态",
  "What this does": "此操作的作用",
  "Rebuilds local project indexes and refreshes project snapshots. Existing chats stay in place.": "重建本地项目索引并刷新项目快照，现有聊天会被保留。",
  "About": "关于",
  "Version": "版本",
  "Current application version.": "当前应用版本。",
  "Release history": "版本历史",
  "A running log of every update, newest first. Same notes the post-update dialog shows, kept here so you can revisit them any time.": "所有更新的连续记录，最新版本在前。这里保留更新后对话框中的说明，方便随时查看。",
  "View release history": "查看版本历史",
  "Every curated release, newest first.": "全部精选发布记录，最新版本在前。",
  "Close": "关闭",
  "Couldn’t load your local stats.": "无法加载本地统计数据。",
  "Try again": "重试",
  "Share": "分享",
  "Edit": "编辑",
  "Lifetime tokens": "累计令牌",
  "Peak day": "最高使用日",
  "Total prompts": "提示总数",
  "Current streak": "当前连续天数",
  "Longest streak": "最长连续天数",
  "Activity": "活动",
  "Activity insights": "活动洞察",
  "Most used provider": "最常用服务商",
  "Most used reasoning": "最常用推理级别",
  "Most active hour": "最活跃时段",
  "Most worked project": "最常使用的项目",
  "Skills explored": "已探索技能",
  "Total skills used": "已使用技能总数",
  "Total threads": "线程总数",
  "Most used plugins": "最常用插件",
  "runs": "次运行",
  "No skills or agents used yet.": "尚未使用技能或代理。",
  "Model usage": "模型用量",
  "No model activity yet.": "尚无模型活动。",
  "Search shortcuts...": "搜索快捷键…",
  "Search shortcuts": "搜索快捷键",
  "Command": "命令",
  "Keybinding": "快捷键",
  "No shortcuts match": "没有匹配的快捷键",
  "Portable skills": "便携技能",
  "Synara skills folder": "Synara 技能文件夹",
  "Skills placed here are available on every provider. When a provider already ships its own copy of a skill, that copy is used; otherwise Synara's copy is the fallback.": "放在这里的技能可用于所有服务商。当服务商已有同名技能副本时，会优先使用该副本；否则使用 Synara 的副本。",
  "Scanning…": "正在扫描…",
  "skills enabled": "个技能已启用",
  "Skill discovery failed": "技能发现失败",
  "Synara could not scan the skill folders. Retry after checking that the server is running.": "Synara 无法扫描技能文件夹。请确认服务器正在运行后重试。",
  "No skills found": "未找到技能",
  "Add a skill folder containing a SKILL.md to the Synara skills folder above, or install skills for any supported provider.": "在上方 Synara 技能文件夹中添加包含 SKILL.md 的技能文件夹，或为任一受支持服务商安装技能。",
  "Enable skill": "启用技能",
  "Provider usage": "服务商用量",
  "Refresh": "刷新",
  "Loading provider usage…": "正在加载服务商用量…",
  "Not signed in": "未登录",
  "Unsupported": "不支持",
  "Unavailable": "不可用",
  "No usage data reported yet.": "尚未报告用量数据。",
  "Usage is currently unavailable.": "当前无法获取用量。",
  "providers hidden": "个服务商已隐藏",
  "Reorder": "调整顺序",
  "Show in provider picker": "在服务商选择器中显示",
  "Manual update": "手动更新",
  "Usage is read locally from each provider CLI's stored credentials and fetched directly from the provider. OAuth providers may refresh short-lived tokens through their official token endpoint; if a provider shows “Not signed in”, re-authenticate with its CLI.": "用量信息从各服务商 CLI 保存的凭据中在本地读取，并直接向服务商获取。OAuth 服务商可能会通过官方令牌端点刷新短期令牌；若显示“未登录”，请通过对应 CLI 重新认证。",
  "Show keyboard shortcuts": "显示键盘快捷键",
  "Open this sheet from anywhere without leaving your current context.": "无需离开当前上下文，即可从任意位置打开此面板。",
  "Add project": "添加项目",
  "Open the folder picker to import a local project into the sidebar.": "打开文件夹选择器，将本地项目导入侧边栏。",
  "Search projects and threads": "搜索项目和线程",
  "Open the sidebar search palette from anywhere in the app.": "从应用任意位置打开侧边栏搜索面板。",
  "Import thread": "导入线程",
  "Bring an existing conversation into the current workspace.": "将现有对话带入当前工作区。",
  "New thread": "新建线程",
  "Start a fresh thread in the current project, or the most recent one.": "在当前项目或最近使用的项目中新建线程。",
  "New thread in latest project": "在最近项目中新建线程",
  "Jump back into the most recently used project with a new thread.": "返回最近使用的项目并新建线程。",
  "New chat": "新建聊天",
  "Open the empty chat landing view.": "打开空白聊天起始页。",
  "New terminal thread": "新建终端线程",
  "Create a thread that opens directly into terminal mode.": "新建一个直接以终端模式打开的线程。",
  "New Claude thread": "新建 Claude 线程",
  "Start a fresh thread with Claude selected.": "新建线程并选择 Claude。",
  "New Codex thread": "新建 Codex 线程",
  "Start a fresh thread with Codex selected.": "新建线程并选择 Codex。",
  "New Cursor thread": "新建 Cursor 线程",
  "Start a fresh thread with Cursor selected.": "新建线程并选择 Cursor。",
  "Split chat": "拆分聊天",
  "Open the current conversation in a second pane.": "在第二个面板中打开当前对话。",
  "Previous recent view": "上一个最近视图",
  "Cycle backward through recently opened primary views.": "在最近打开的主视图之间向后切换。",
  "Next recent view": "下一个最近视图",
  "Cycle forward through recently opened primary views.": "在最近打开的主视图之间向前切换。",
  "Model picker": "模型选择器",
  "Open the composer provider and model picker.": "打开输入框的服务商与模型选择器。",
  "Next model": "下一个模型",
  "Cycle to the next model for the active provider (favorites first, then remaining models).": "切换到当前服务商的下一个模型（先收藏，后其他模型）。",
  "Previous model": "上一个模型",
  "Cycle to the previous model for the active provider (favorites first, then remaining models).": "切换到当前服务商的上一个模型（先收藏，后其他模型）。",
  "Reasoning picker": "推理选择器",
  "Open the composer reasoning and trait controls.": "打开输入框的推理与特征控制项。",
  "Focus composer": "聚焦输入框",
  "Focus or blur the chat prompt composer.": "聚焦或取消聚焦聊天提示输入框。",
  "Toggle terminal": "切换终端",
  "Show or hide the terminal surface for the active thread.": "显示或隐藏当前线程的终端区域。",
  "Toggle diff": "切换差异视图",
  "Open or close the working tree diff panel.": "打开或关闭工作树差异面板。",
  "Toggle browser": "切换浏览器",
  "Reveal the built-in browser panel for the active thread.": "显示当前线程的内置浏览器面板。",
  "Previous visible thread": "上一个可见线程",
  "Cycle to the previous thread that is currently visible in the sidebar.": "切换到侧边栏当前可见的上一个线程。",
  "Next visible thread": "下一个可见线程",
  "Cycle to the next thread that is currently visible in the sidebar.": "切换到侧边栏当前可见的下一个线程。",
  "Open in favorite editor": "在首选编辑器中打开",
  "Send the current thread or workspace target to your preferred editor.": "将当前线程或工作区目标发送到首选编辑器。",
  "Focus a visible thread directly from the sidebar number row.": "通过侧边栏数字行直接聚焦可见线程。",
  "Open full-width terminal workspace": "打开全宽终端工作区",
  "Expand the active thread into the workspace terminal layout.": "将当前线程展开为工作区终端布局。",
  "Focus terminal tab": "聚焦终端标签页",
  "Switch the workspace to the terminal tab.": "切换工作区到终端标签页。",
  "Focus chat tab": "聚焦聊天标签页",
  "Switch the workspace back to the chat tab.": "将工作区切回聊天标签页。",
  "Close active workspace panel": "关闭活动工作区面板",
  "Close the currently focused workspace panel or tab.": "关闭当前聚焦的工作区面板或标签页。",
  "Toggle sidebar": "切换侧边栏",
  "Collapse or reveal the sidebar shell.": "收起或展开侧边栏。",
  "Jump to visible thread": "跳转到可见线程",
  "Wrap diff lines by default": "默认换行显示差异行",
  "Terminal font size in pixels": "终端字号（像素）",
  "Projects": "项目",
  "New project": "新建项目",
  "New workspace": "新建工作区",
  "New studio chat": "新建工作室聊天",
  "Search": "搜索",
  "Kanban": "看板",
  "Pull requests": "拉取请求",
  "Automations": "自动化",
  "No studio chats yet": "尚无工作室聊天",
  "Loading Studio...": "正在加载工作室…",
  "No projects yet": "尚无项目",
  "Open new chat home": "打开新聊天主页",
  "No chats yet": "尚无聊天",
  "Settings": "设置",
  "New Chat": "新建聊天",
  "What should we work on?": "我们来做什么？",
  "What should we do in": "我们在这里做什么？",
  "this folder": "此文件夹",
  "Ask for follow-up changes": "输入后续修改要求",
  "Ask for follow-up changes or attach images": "输入后续修改要求或附加图片",
  "Ask anything, @tag files/folders, or use / to show available commands": "输入任何问题，@ 标记文件/文件夹，或使用 / 查看可用命令",
  "Work in a project": "在项目中工作",
  "Resolve this approval request to continue": "处理此审批请求后继续",
  "Type your answer to continue": "输入你的回答以继续",
  "Type your own answer, or leave this blank to use the selected option": "输入你的回答；留空则使用已选选项",
  "Add feedback to refine the plan, or leave this blank to implement it": "添加反馈以完善计划；留空则直接实施",
  "Message this subagent while it works": "在子代理工作时向它发送消息",
  "Full access": "完全访问",
  "Default permissions": "默认权限",
  "Full access — click to change permissions": "完全访问 — 点击可更改权限",
  "Default permissions — click to change permissions": "默认权限 — 点击可更改权限",
};

export function resolveUiLanguage(
  preference: UiLanguagePreference,
  systemLanguages: readonly string[] = globalThis.navigator?.languages ?? [],
): ResolvedUiLanguage {
  if (preference !== "system") return preference;
  return systemLanguages.some((language) => language.toLowerCase().startsWith("zh"))
    ? "zh-CN"
    : "en";
}

export function translateUiText(language: ResolvedUiLanguage, text: string): string {
  return language === "zh-CN" ? (SIMPLIFIED_CHINESE_TEXT[text] ?? text) : text;
}
